---
title: "TUP_report"
author: "Reajul Chowdhury, Elliott Collins, Ethan A. Ligon, Munshi Sulaiman"
date: "December 03, 2018"
output:
  html_document: default
  pdf_document:
    keep_tex: yes
bibliography: /Users/reajul/Desktop/TUP_2018_CEGA/TUP_intro_reference.bib
---

```{r setup, include=FALSE}
library (knitr)
opts_chunk$set(echo = TRUE)
```

# Introduction
Despite remarkable progress on reducing poverty over the last decades, the United Nations (UN) and the World Bank admit that we are far behind and might fail in achieving the goal of ending extreme poverty^[population living on less than US$1.90 a day] by 2030 [@WorldBank2018]. The reasons behind this slow progress are mainly two. First, it is difficult to reach the poor - specially the poorest among the poor. Second, development models or interventions which effectively alleviate poverty and provide sustainable livelihoods to extreme poor are rare in number. So, the biggest challenge in poverty alleviation is reaching the ‘poorest’ with an ‘effective’ intervention. The poorest or the ‘ultra-poor’^[The term ultra-poor was coined by Lipton (1983) in reference to a group of people that spend 80 per cent of their total income for food and eat below 80 per cent of their caloric needs. Later, a report by the International Food Policy Research Institute, defined as ultra-poor those living with less than US$0.50 a day [@Ahmed2007]] people are the most vulnerable subgroup within the population living under extreme poverty line. They are severely food insecure, own little or no productive assets, have no education and skills, and earn money from low return activities like small-scale cultivation or causal day labor.


NGOs and development organizations tried to help the ultra-poor households with traditional microcredit product - which is a proven tool in reducing vulnerability, creating economic opportunities, and increasing income of poor people by giving them access to finance [@Hashemi2011]. But the traditional microcredit does not fit the needs of the poorest, and has failed to reach the ultra-poor [@Hashemi2011]. Microcredit products are mainly small, high-interest loans, usually designed for micro entrepreneurs- who are already involved with or more likely to start some self-employment activities, and will be able to make use of the credit to take advantage of market opportunities [@Banerjee2015; @Hashemi2011]. The ultra-poor households are much poorer than the targeted groups of microcredit providers and therefore, have been excluded from the  most microcredit programs [@Evans1999; @Thorp2005; @Kaur2016]. Even when offered with microcredit, the ultra-poor households lack the human capital and entrepreneurial skills to effectively use the credit, and might fall in credit-based poverty trap. Another strategy through which governments and donor organizations reach the ultra-poor is safety net programs such as food aid, school feeding, temporary employment programs, free health services, unemployment benefits, pensions, etc. Countries hosting most of the world’s poor population cannot often afford such safety net programs in long run. The safety net programs often fail to reach the ultra-poor^[Evidence shows that India’s Integrated Rural Development Program (IRDP) had poor performance in targeting the poorest.[@Dreze1990; @Pulley1989]]. Such programs are also widely criticized for focusing only on protecting the poor rather than helping them to improve their livelihoods and get out of extreme poverty. 


Over the last few decades, NGOs and development organizations learned that a single product or service cannot fit the dynamic needs of the ultra-poor and help them overcoming extreme poverty. Giving them a sustainable livelihoods will require a comprehensive, integrated set of interventions. Building on this insight, BRAC – a Bangladesh origin NGO, pioneered a program called Targeting the Ultra-poor (TUP) to build secure, sustainable, and resilient livelihoods for the ultra-poor. The TUP program follows a ‘Graduation’ approach that combines multifaceted support services addressing both immediate needs of the ultra-poor by giving them consumption supports, and their long-term need for a sustainable livelihoods by providing technical skills training, and a grant of productive assets. BRAC first implemented the TUP program in 2002 in Bangladesh. Several non-experimental studies [@Ahmed2009; @Mallick2013; @Matin2003; @Rabbani2006]  found the TUP program very effective in increasing household consumption, assets holdings, and self-employment among the ultra-poor. The holistic treatment of poverty in the Graduation approach (or BRAC’s TUP program) drew the attention of the donor community, and other stakeholders in the extreme poverty affected countries. The TUP model has later been replicated and adapted by 114 programs in 45 countries by NGOs, governments, and donor organizations^[BRAC website: http://www.brac.net/program/targeting-ultra-poor/] . Through its TUP program in Bangladesh, BRAC alone reached a total of 1.77 million ultra-poor households till 2016, and aims to reach 0.5 million more households by 2020^[http://www.brac.net/images/index/tup/brac_TUP-briefNote-Jun17.pdf]. 


Taking advantage of the large scale replication of the TUP program in Bangladesh and other countries, a number of experimental studies ( (Banarjee, Duflo, Chattopadhyay, & Shapiro, 2011) [@Voropaeva1966; @Bandiera2013; @Bandiera2017; @Banerjee2015] have been conducted to assess the impact of the program. In Bangladesh, Bandiera et al. (2013) found that after four years of the program inception, the beneficiary households expanded their self-employment activities, increased labor supply, accumulated more productive assets, which led to increased household income and per capita consumption. A follow-up survey on the same households seven years after the program began, found that the long-term effect of the program is at least as large as the four-years effect [@Bandiera2017]. Banarjee et al. (2015) documented the findings from 6 randomized trail studies assessing the impact of the TUP program implemented in 6 countries^[Ethiopia, Ghana, Honduras, India, Pakistan, and Peru]. The study found effect of the program on income, assets holdings, food security, and consumption similar to the Bangladesh study. 


While the graduation approach (BRAC’s TUP model) was getting popular and being replicated in many countries, Haushofer & Shapiro (2013), and Chrsi Blattman et al. (2015) were experimenting the effect of a very simple unconditional cash transfer (UCT) to help the ultra-poor households fighting extreme poverty in Kenya and Uganda. The rational for such simple cash transfer is straight forward – putting the development and social protection resources directly in the hands of poor people and let them fight the dimensions of poverty in their own way. Findings from both studies show significant effect of the cash transfer on assets holdings (both productive and overall household assets), consumption, and food security. For instance, the study from Kenya found that compared to the control group mean, the recipients’  total assets holding increased by 58%, and household consumption increased by 20% (Haushofer & Shapiro,2013). A three-years follow up survey on these households show a similar magnitude of effects persist on the same welfare outcomes (Haushofer & Shapiro, 2018). The study in Uganda also found the unconditional cash transfer to be effective in terms of increased self-employment activities, assets holdings, and consumption of the recipients [@Blattman2016]. Though whether such unconditional cash transfer can offer sustainable routs out of poverty on a large scale still remains a question, the low operational costs and significant effect on particular welfare outcomes (at least in short run) made such transfer program an attractive alternative to relatively more expensive Graduation approach/BRAC’s TUP model. These two competitive approaches of transfer program put an obvious question to the development economists – is it worth to invest on the additional features of the TUP framework and which type of transfer is more effective in a given context. 


In this paper, we present results from a randomized trial study comparing the BRAC’s TUP program with unconditional cash transfers in South Sudan. We aim to answer the research questions – **does the type of transfer matter and do the different types of transfer result different welfare change?** Our results contribute to the general literature in two important ways. First, to the best of our knowledge, this is the first experiment attempting to directly compare these two competitive approaches of transfer programs in the same setup. In our study, a randomly selected group of households received cash transfers equal in market value to the assets provided to the TUP households. Second, South Sudan’s long-history of ongoing conflict and volatile economy, which may affect the value of the program for households in important ways. South Sudan earned its independence after five decades of civil war with North Sudan. The youngest nation of the world had some of the worst development indicators in the world; under five and maternal mortality in the county is world’s highest [@WHO2014], the whole country has only 124 miles of paved road, the unemployment rate in the country is one of the highest in the world. The country fall into another civil war that broke out in December, 2013. After the latest round of the civil war, around 1.74 million people have been internally displaced, and 640,000 people took refuges in the neighboring countries^[https://reliefweb.int/report/south-sudan/south-sudan-humanitarian-bulletin-issue-6-16-july-2018] . The government had little control on the market, and the economy experienced unprecedented hyperinflation over the last 5 years…………



#### Works Cited
